on:
    push:
        branches:
            - main

name: ⏫ Copy content to Destination

jobs:
    copy-file:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            # Copy the 'backend' folder
            - name: Push posts
              uses: dmnemec/copy_file_to_another_repo_action@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                  source_file: "kube-backend/" # Folder to copy
                  destination_repo: "shahedex/destination" # Target repo
                  destination_folder: "/" # Folder where to copy it
                  user_email: "shahed739@gmail.com"
                  user_name: "shahedex"
                  commit_message: ${{ github.event.head_commit.message }}
                  git_server: "github.com"
